In [1]:
import pandas as pd
import numpy as np
movies_df=pd.read_csv(r'C:\Users\Acer\Desktop\Data_Science_Projects\Recommender system\Collaborative_Filtering\data\movies.csv')
ratings_df=pd.read_csv(r'C:\Users\Acer\Desktop\Data_Science_Projects\Recommender system\Collaborative_Filtering\data\ratings.csv')
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [2]:
#select a user
import random
userId=random.choice(ratings_df['userId'].unique())
print("Selected User :",userId)

Selected User : 210

In [3]:
userRatings=ratings_df[ratings_df['userId']==userId]
userRatings.head()

       userId  movieId  rating   timestamp
30042     210      153     3.5  1527266231
30043     210      260     5.0  1473705468
30044     210      296     0.5  1473705619
30045     210      435     1.5  1537087956
30046     210      485     3.5  1475508204

In [4]:
#create user-movie matrix
userMovieMatrix=ratings_df.pivot_table(index='userId',
                                       columns='movieId',
                                       values='rating')
userMovieMatrix.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Fill missing values
userMovieMatrix=userMovieMatrix.fillna(0)
userMovieMatrix.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
#compute similarity between users
from sklearn.metrics.pairwise import cosine_similarity
userSimilarity=cosine_similarity(userMovieMatrix)
userSimilarity_df=pd.DataFrame(userSimilarity,
index=userMovieMatrix.index,
columns=userMovieMatrix.index)
userSimilarity_df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792

In [8]:
#find similar users
similarUsers=userSimilarity_df[userId].sort_values(ascending=False)
similarUsers.head(10)

userId
210    1.000000
475    0.367465
586    0.330501
596    0.290674
582    0.276454
77     0.275412
62     0.271736
15     0.267601
30     0.261536
466    0.259299
Name: 210, dtype: float64

In [10]:
topUsers=similarUsers.iloc[1:6].index
topUsers

Index([475, 586, 596, 582, 77], dtype='int64', name='userId')

In [11]:
#Get movies They liked
topUsersRatings=ratings_df[ratings_df['userId'].isin(topUsers)]
topUsersRatings.head()

       userId  movieId  rating   timestamp
12383      77      260     5.0  1535107459
12384      77     1196     5.0  1535107474
12385      77     1198     5.0  1535107476
12386      77     1210     5.0  1535107480
12387      77     2571     5.0  1535107478

In [12]:
#Compute wighted recommendation
topUsersRatings=topUsersRatings.merge(similarUsers.rename('similarity'),
                                      left_on='userId',
                                      right_index=True)
topUsersRatings.head()

       userId  movieId  rating   timestamp  similarity
12383      77      260     5.0  1535107459    0.275412
12384      77     1196     5.0  1535107474    0.275412
12385      77     1198     5.0  1535107476    0.275412
12386      77     1210     5.0  1535107480    0.275412
12387      77     2571     5.0  1535107478    0.275412

In [13]:
#Calculate weighted score
topUsersRatings['weightedRating']=topUsersRatings['rating']*topUsersRatings['similarity']

In [21]:
#Aggregate Scores per movie
recommendation_df=topUsersRatings.groupby('movieId')['weightedRating'].sum().reset_index()
recommendation_df.head()

   movieId  weightedRating
0        1        1.162697
1        2        2.975594
2       19        1.469859
3       32        1.017360
4       34        1.162697

In [22]:
#sort recommendations
recommendation_df=recommendation_df.sort_values(by='weightedRating',ascending=False)
recommendation_df.head(10)

     movieId  weightedRating
141     2571        7.228121
225     4993        6.997172
15       260        6.970149
61      1196        6.824812
357    58559        6.557179
270     7153        5.884246
244     5952        5.884246
63      1198        5.884246
65      1210        5.864333
512   122886        5.858172

In [23]:
#remove already watched movies
watched_movies=userRatings['movieId'].tolist()

In [24]:
#remove from recommendation
recommendation_df=recommendation_df[~recommendation_df['movieId'].isin(watched_movies)]

In [25]:
#Add movies names
recommendation_df=recommendation_df.merge(movies_df[['movieId','title']],on='movieId')

In [26]:
#Sort and show final top 10
final_recommendations=recommendation_df.sort_values(
    by='weightedRating',
    ascending=False
)
final_recommendations[['title','weightedRating']].head(10)

                                              title  weightedRating
0                                  Gladiator (2000)        5.738909
1                              Batman Begins (2005)        5.515350
2  Harry Potter and the Order of the Phoenix (2007)        5.264020
3                     Dark Knight Rises, The (2012)        5.218515
4                      Bourne Ultimatum, The (2007)        5.129777
5                               Interstellar (2014)        4.832910
6                                      X-Men (2000)        4.652524
7   Harry Potter and the Prisoner of Azkaban (2004)        4.550138
8                       Bourne Identity, The (2002)        4.516233
9                                   Zootopia (2016)        4.468791